### ISSUE TITLE
Tilesets editor: Allow to copy tiles selections by dragging them.

### ISSUE THREAD

**Issue by maxamine** [solarus-games/solarus-quest-editor#122]
Currently when we drag an existing selection in the tilesets editor it offers us to move it to the new area or to cancel the operation. it would be useful if the tool offers us to copy the selection in order to paste it in multiple areas such as in sprite editor. it will be helpful to accelerate the creation of the selections.
Also (Ctrl+C / Ctrl+V) can be used to copy and paste the selections.

**Comment by christopho** [comment]
Done in 1.6
