### ISSUE TITLE
Enhancement: Allow to resize with "R"+"Mouse" in the Sprite Editor

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/solarus-quest-editor#147]
Allow to resize with "R"+"Mouse" in the Sprite Editor, in the same way as it is possible for some entities in the map Editor.

**Comment by Maxs1789** [comment]
What do you mean exactly by `"resize"` in the SpriteEditor ?

- **Resize the frame size**
Not easy to implement and I think that's easier to use the spinboxes because the frames can have any size.

- **Change the number of frames/columns**
It can be a useful feature ! And maybe can we add a `"new multiframe direction"` action when we create a direction to directly set the frames/columns number.

**Comment by Diarandor** [comment]
Hi @Maxs1789, I did not explain this well.

I was refering to the first case, "resizing the frame size", but you are completely right that this is not so good since sizes can take any value (not only multiples of 8), so using the mouse would not be that good because it is not so precise. So maybe it is better not to implement this for the sprites (although it would be nice to implement this for the tilesets, but this would be a different issue).

However, your idea of "changing the number of frames/columns" could be very nice, I agree. Maybe we should either rename this issue for this second feature, or just close the issue.

**Comment by Maxs1789** [comment]
For the tilesets, there are already an issue (#159).

Now I'm thinking of this and the only problem could be that the frame number will be a multiple of the column number, maybe that we can have several actions:

1. **Change the number of frames/columns** (frame number multiple of column number)
2. **Change the number of frames** (column number fixed)
3. **Change the number of columns** (frame number fixed)

We can use the first case by default (when creating sprite) and have the choice in the context menu.

What do you think ? Have the choice or not ? If not, which one ?

**Comment by Diarandor** [comment]
You are right, the frame number is not necessarily a multiple of the column number, which may be a problem (or not). In the last list you gave, both options 1 and 2 may be good for a default behavior if we add this feature (we should choose one of them). If we give the possibility of changing to the other two, we could also allow to choose the default behavior in Tools -> Options -> Sprite Editor, appart from the context menu, maybe?

**Comment by christopho** [comment]
The column number and the frame number are equal in 99% of my sprites.
