### ISSUE TITLE
Bug: Sprite animation preview greater lag and walking yellow coordinate blocks not moving issues

### ISSUE THREAD

**Issue by Zefk** [solarus-games/solarus-quest-editor#177]
With the recent 1.5 Solarus version there is a greater lag (Longer lag than before) for a few seconds before the animation previews correctly. Also, I could not move the yellow coordinate blocks with my mouse for the walking animation. I entered it manually with the input options. I had no issues in the last 1.5 version.

**Comment by alexander-b** [comment]
What do you mean by "correctly"? It previews immediately for me. So if this is your issue, you should tell us more about what version you are running, and on what system you are running it.

By the "walking yellow coordinate blocks", are you talking about the animation as selected in the sprite preview window? (Those are blue for me, they could very well be yellow for you, I don't know that. A screenshot would be helpful.)

**Comment by Zefk** [comment]
The blue blocks turn yellow when they are being moved. I can not replicate the movement error, but the animation preview lag still exists on both of my computers. Look at the animation preview for about one minute. If there is really no lag, then it might be because I am using Wine.
![selection_001](https://cloud.githubusercontent.com/assets/19560764/15913641/12b0d94a-2d90-11e6-8c02-af5697d38d9b.png)

**Comment by Zefk** [comment]
It seems this issue no longer occurs. I am closing this.
