### ISSUE TITLE
Feature Request: Tileset GUI Setup 8x8 Dimension Change

### ISSUE THREAD

**Issue by Zefk** [solarus-games/solarus-quest-editor#180]
The 8x8 selecting area is great, but some images might need further dimension changes. A grid like option where changes to the 8x8 would save time for developers when putting together tilesets. That way they will not need to make hundreds of adjustments. For example, there could be a checkbox where the developer can click and change the dimension to 1x1, 2x2, 4x4, 4x6, and etc. I think the 8x8 will be fine for default.

Notes: This might require abilities to zoom further and grids would have to go below 8x8.

![4x4](https://cloud.githubusercontent.com/assets/19560764/15658490/e2a20348-2671-11e6-90c1-d50ce7967677.png)

**Comment by christopho** [comment]
But 8x8 is the base unit for obstacles with tiles. All tile patterns should be multiples of 8x8.

**Comment by Zefk** [comment]
That is why I opened this issue #176 to show some issues with manual adjustment. It kinda takes quite a bit of time to move or reformat graphics to be 8x8 compatible without lots of trial and errors...even with a 8x8 grid.

**Comment by alexander-b** [comment]
It has to be 8x8, but maybe we can allow users to input x/y offsets to tilesets?

**Comment by Zefk** [comment]
That is kinda already exists if I am understanding what you are saying. #176

I clicked pieces and adjusted the coordinates before making it 8x8. It was an error I made.

**Comment by Zefk** [comment]
> But 8x8 is the base unit for obstacles with tiles. All tile patterns should be multiples of 8x8.

I agree with Christopho's comment and will close this.
