### ISSUE TITLE
Tileset editor: allow to duplicate multiple patterns at once

### ISSUE THREAD

**Issue by Zefk** [solarus-games/solarus-quest-editor#188]
I think this will go well with issue  #171

I have lot of trees (orange box on image) with the same shape, but different color variations and I wish that one could just copy the same 8x8 blue borders (red box on image) over and over again.

![copy 8x8 blue box border selections](https://cloud.githubusercontent.com/assets/19560764/15796495/7e957fde-29b3-11e6-8fc5-8d58b4880bc9.png)

**Comment by christopho** [comment]
@Maxs1789 This is the next step :)
