### ISSUE TITLE
Feature: allow to put a locked semi-transparant background image as a skech

### ISSUE THREAD

**Issue by maxamine** [solarus-games/solarus-quest-editor#244]
in addition to backgound color, it would be time saver if the editor allows to put a semi-transparant background image as a skech, and also a transpatent background.
This tool must also allow users to lock the background image so that it doesn't move when mapping. (This is purely in the editor, not in the map file).

See the screenshots below:

![qsqs](https://cloud.githubusercontent.com/assets/14140919/19213650/f0abbbba-8d68-11e6-8ed0-d6b1e4936a74.png)

![qqss](https://cloud.githubusercontent.com/assets/14140919/19213696/b2bd3ea8-8d6a-11e6-829a-57a0038265ee.png)

**Comment by christopho** [comment]
Note that this is purely in the editor, not in the map file.

**Comment by christopho** [comment]
It is already possible to make an entity that show any image. Now that negative layers are supported and with #94, we can close this issue.
