### ISSUE TITLE
Editor does not show .dat files in the scripts directory

### ISSUE THREAD

**Issue by llamaizing** [solarus-games/solarus-quest-editor#260]
I've been using the convention of giving a script a .lua extension and specifying any quest-specific data pertinent to the script in a separate file with the same name except with a .dat extension (returns a table with static data values). This has the benefit of not needing to modify the script itself when configuring it with quest-specific data provided that only minor tweaks to the script are necessary.

In the ALTTP resource pack, for example, there are two scripts: data/scripts/hud/hud.lua and data/scripts/hud/hud_config.lua, where the hud_config.lua simply returns a table that specifies where on the hud to draw each of the hud elements used by hud.lua. My convention would be to rename hud_config.lua to hud.dat, as it provides quest-specific data used by hud.lua. Additional examples can be found in this project of mine: https://github.com/llamaizing/cythera-tech-demo

However, the quest editor does not show files with the .dat extension that are located in the scripts directory. It doesn't bother me specifically, as I use an external text editor to edit the script files anyway, but it may hinder the average user who is viewing/modifying my quest data.

**Comment by Diarandor** [comment]
Some ideas: we could allow this feature as optional, allowing to enable/disable it from the options window. (Also, a context menu to open these dat files in the default text editor would be useful. Of course, there should be an option to open them with the quest editor too.)

**Comment by christopho** [comment]
Similarly, we should have an option to show PNG files in the tree.
