### ISSUE TITLE
Find and replace in the code editor

### ISSUE THREAD

**Issue by christopho** [solarus-games/solarus-quest-editor#3]
Implement a find and replace feature in the script editor.

**Comment by christopho** [comment]
A basic find dialog was added to 1.4. More find options (case sensitivity, regexps, backward search) and a replace feature should be done in 1.5.

**Comment by wrightmat** [comment]
In the find dialog, the default button should be "Find" and not "Cancel" - that way when you hit enter it shows results instead of closing the dialog.

**Comment by christopho** [comment]
Right, I opened another issue for that: #30

**Comment by Maxs1789** [comment]
We could also add an option to search in all scripts of the quest. Or maybe in another dialog.

**Comment by christopho** [comment]
Another dialog then.
