### ISSUE TITLE
Map editor: Allow to display the tile layer without opening the tile properties

### ISSUE THREAD

**Issue by maxamine** [solarus-games/solarus-quest-editor#91]
It would be nice to display tile layer in the bottom of the map such as tiles position.

![sans titre](https://cloud.githubusercontent.com/assets/14140919/9733215/596c654e-5621-11e5-9bba-188e87f9a1af.png)

**Comment by christopho** [comment]
Did you already program it or did you modify your screenshot? If you already programmed it, a pull request is welcome.

**Comment by maxamine** [comment]
no i didn't, i'm a designer, i just did it in photoshop to show it to u

**Comment by christopho** [comment]
Ok :)
Maybe it should be displayed near the coordinates, because the layer can be seen as a z-coordinate.

**Comment by maxamine** [comment]
good idea
